test(ci): check major podman version is 5
Signed-off-by: Simon Rey <sfbrey+eqqe@gmail.com>

diff --git a/.github/workflows/e2e-main.yaml b/.github/workflows/e2e-main.yaml
--- a/.github/workflows/e2e-main.yaml
+++ b/.github/workflows/e2e-main.yaml
@@ -106,7 +106,37 @@ jobs:
             curl -L "http://ftp.lysator.liu.se/pub/opensuse/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/Release.key" | sudo apt-key add - && \
             sudo apt-get update && \
             sudo apt-get -y install podman; }
+      - name: Update podman to 5.x
+        run: |
+          echo "ubuntu version from kubic repository to install podman we need (v5)"
+          ubuntu_version='23.10'
+          echo "Add unstable kubic repo into list of available sources and get the repo key"
+          sudo sh -c "echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list"
+          curl -L "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/Release.key" | sudo apt-key add -
+          echo "Updating all dependencies..."
+          sudo apt-get update -qq
+          echo "install necessary dependencies for criu package which is not part of ${ubuntu_version}"
+          sudo apt-get install --allow-unauthenticated -qq libprotobuf32t64 python3-protobuf libnet1
+          echo "install criu manually from static location"
+          curl -sLO http://cz.archive.ubuntu.com/ubuntu/pool/universe/c/criu/criu_3.16.1-2_amd64.deb && sudo dpkg -i criu_3.16.1-2_amd64.deb
+          echo "installing/update podman package..."
+          sudo apt-get -qq -y install --allow-unauthenticated podman || { echo "Start fallback steps for podman nightly installation from a static mirror" && \
+            sudo sh -c "echo 'deb http://ftp.lysator.liu.se/pub/opensuse/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list" && \
+            curl -L "http://ftp.lysator.liu.se/pub/opensuse/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/Release.key" | sudo apt-key add - && \
+            sudo apt-get --allow-insecure-repositories update && \
+            sudo apt-get --allow-unauthenticated -y install podman; }
+          
+          # Display Podman version
           podman version
+          
+          # Check if the major version is 5
+          PODMAN_VERSION=$(podman version | grep 'Version:' | awk '{print $2}')
+          if [[ "$PODMAN_VERSION" == 5.* ]]; then
+            echo "Podman major version is 5. Proceeding with the workflow."
+          else
+            echo "Error: Podman major version is not 5. Found: $PODMAN_VERSION"
+            exit 1 # Fail the step if the condition is not met
+          fi
 
       - name: Revert unprivileged user namespace restrictions in Ubuntu 24.04
         run: |
